# -*- coding: utf-8 -*-
"""Git_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a72gfGlBztftc61WzSTwDE8l0MpjnSWh
"""

def main():
  print('This is main')